/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next')['BButtonGroup']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BListGroupItem: typeof import('bootstrap-vue-next')['BListGroupItem']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    ErrorBox: typeof import('./src/components/ErrorBox.vue')['default']
    HomeView: typeof import('./src/components/views/HomeView.vue')['default']
    LoadingIndicator: typeof import('./src/components/LoadingIndicator.vue')['default']
    MangaDetailsCard: typeof import('./src/components/manga/MangaDetailsCard.vue')['default']
    MangaDetailsView: typeof import('./src/components/views/MangaDetailsView.vue')['default']
    MangaImageScroll: typeof import('./src/components/reader/MangaImageScroll.vue')['default']
    MangaNav: typeof import('./src/components/reader/MangaNav.vue')['default']
    MangaReader: typeof import('./src/components/views/MangaReader.vue')['default']
    MangaSearchPreview: typeof import('./src/components/manga/MangaSearchPreview.vue')['default']
    Navbar: typeof import('./src/components/navbar/Navbar.vue')['default']
    NavBreadcrumbs: typeof import('./src/components/navbar/NavBreadcrumbs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/home/SearchBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
  }
}
